export const styles = {
  gameContainer: {
    width: '100vw',
    height: '100vh',
    position: 'relative',
    backgroundColor: '#000',
    fontFamily: "'Poppins', sans-serif",
    color: '#fff',
  },
  leftControls: {
    position: 'absolute',
    bottom: '100px',
    left: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '15px',
    zIndex: 1000,
  },
  rightControls: {
    position: 'absolute',
    bottom: '100px',
    right: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '15px',
    zIndex: 1000,
  },
  FlyControls: {
    position: 'absolute',
    bottom: '300px',
    right: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '15px',
    zIndex: 1000,
  },
  controlBtn: {
    width: 60,
    height: 60,
    fontSize: '2em',
    color: '#fff',
    border: '2px solid #fff',
    borderRadius: '50%',
    alignItems: 'center',
    touchAction: 'none',
    backgroundColor: '#09959F'
  },
  hud: {
    position: 'absolute',
    top: '20px',
    left: '20px',
    right: '20px',
    display: 'flex',
    justifyContent: 'space-between',
    pointerEvents: 'none',
    textShadow: '2px 2px 4px rgba(0,0,0,0.7)',
  },
  hudItem: {
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    padding: '10px 20px',
    borderRadius: '10px',
    border: '2px solid rgba(255, 255, 255, 0.3)',
  },
  speedometer: {
    fontSize: '2em',
    fontWeight: 'bold',
  },
  lapCounter: {
    fontSize: '2em',
    fontWeight: 'bold',
  },
  messageDisplay: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    fontSize: '5em',
    fontWeight: 'bold',
    color: '#ffc400',
    textShadow: '3px 3px 6px rgba(0,0,0,0.8)',
    pointerEvents: 'none',
    textAlign: 'center',
  },
  controlsInfo: {
    position: 'absolute',
    bottom: '20px',
    left: '50%',
    transform: 'translateX(-50%)',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    padding: '15px',
    borderRadius: '10px',
    fontSize: '1.2em',
    textAlign: 'center',
  },
};